name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          version: '21.2.0'
          java-version: '17'
      - run: ./gradlew build --stacktrace
      - run: ./gradlew nativeCompile --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
